### PR TITLE
fix(*): Cleanup funnel state when unmounted

### LINKED ISSUE #85: [Bug]: Issue at using sub funnel when re-entered
### Package Scope

@use-funnel/core

### Bug description

When using sub funnel re-entered, the sub funnel query string is alived, should not start at the initial step

Example) When A Funnel 1st, 3rd using B Funnel

A Funnel, 1st Step -> B Funnel, 1st Step -> B Funnel, 2nd Step -> A Funnel, 2nd Step -> A Funnel 3rd Step -> B Funnel, 2nd Step (??)

### Expected behavior

_No response_

### To Reproduce

_No response_

### Possible Solution

_No response_

### etc.

_No response_

### PR DESCRIPTION
**Pull request by minuukang**
close #85 

Add a interface of `cleanup()` when funnel is unmounted.

**NOTE: The `@use-funnel/react-navigation-native` should don't use this interface at push stack navigation because the navigation stack render is still alive.**
so, check all funnel route param and remove when is not current route.

### CODE REVIEW

File: packages/browser/src/index.ts [hunk 1]
```diff
@@ -74,10 +75,23 @@ export const useFunnel = createUseFunnel(({ id, initialState }) => {
...
+          ...window.history.state,
+        };
+
+        delete newHistoryState[`${id}.context`];
+        delete newHistoryState[`${id}.histories`];
+
+        const searchParams = new URLSearchParams(location.search);
+        searchParams.delete(`${id}.step`);
+
+        window.history.replaceState(newHistoryState, '', `?${searchParams.toString()}`);
```
Comment (minuukang) [inline packages/browser/src/index.ts:92]: from #95
